peer0.${orgAdd}:
  container_name: peer0.${orgAdd}
  image: hyperledger/fabric-peer:latest
  environment:
      #Generic peer variables
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${networkname}
    - FABRIC_LOGGING_SPEC=INFO
    #- FABRIC_LOGGING_SPEC=DEBUG
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    # Peer specific variabes
    - CORE_PEER_ID=peer0.${orgAdd}
    - CORE_PEER_ADDRESS=peer0.${orgAdd}:${peerport}
    - CORE_PEER_LISTENADDRESS=0.0.0.0:${peerport}
    - CORE_PEER_CHAINCODEADDRESS=peer0.${orgAdd}:${peerportnext}
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${peerportnext}
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.${orgAdd}:${peerport}
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.${orgAdd}:${peerport}
    - CORE_PEER_LOCALMSPID=${org}MSP
    - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:1${peerport}
  volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/${orgAdd}/peers/peer0.${orgAdd}/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/${orgAdd}/peers/peer0.${orgAdd}/tls:/etc/hyperledger/fabric/tls
      - peer0.${orgAdd}:/var/hyperledger/production
  working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  command: peer node start
  ports:
    - ${peerport}:${peerport}
    - 1${peerport}:1${peerport}
  networks:
    - ${networknick}